<%-- 
    Document   : Client
    Created on : Dec 7, 2019, 11:14:54 AM
    Author     : simon
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title>JSP Page</title>
    </head>
    <body>
        <div id="form_container">
	
		<h1><a>Client</a></h1>
		<form  method="post" action="">
					<div class="form_description">
			<h2>Nouveau client</h2>
			<p>Formulaire de création d'un nouveau client</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label  for="lastname">Nom : </label>
		<div>
			<input id="lastname" name="lastname" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label  for="firstname">Prénom : </label>
		<div>
			<input id="firstname" name="firstname" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label for="address">Adresse : </label>
		<div>
			<input id="address" name="address" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label for="phone">N° de Téléphone :  </label>
		<div>
			<input id="phone" name="phone" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_5" >
		<label for="email">Email : </label>
		<div>
			<input id="email" name="email" type="text" maxlength="255" value=""/> 
		</div> 
		</li>
			
					<li class="buttons">
			    
				<input id="saveForm" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
    </body>
</html>
