<%-- 
    Document   : Client
    Created on : Dec 7, 2019, 11:14:54 AM
    Author     : simon
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title>JSP Page</title>
    </head>
    <body>
        <div id="form_container">
	
		<h1><a>Client</a></h1>
		<form id="form_92026"  method="post" action="">
					<div class="form_description">
			<h2>Nouveau client</h2>
			<p>Formulaire de création d'un nouveau client</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label  for="element_1">Nom : </label>
		<div>
			<input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label  for="element_2">Prénom : </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label for="element_3">Adresse : </label>
		<div>
			<input id="element_3" name="element_3" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label for="element_4">N° de Téléphone :  </label>
		<div>
			<input id="element_4" name="element_4" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_5" >
		<label for="element_5">Email : </label>
		<div>
			<input id="element_5" name="element_5" type="text" maxlength="255" value=""/> 
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="92026" />
			    
				<input id="saveForm" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
    </body>
</html>
