<%-- 
    Document   : CourseSession
    Created on : Dec 7, 2019, 11:14:54 AM
    Author     : simon
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title>JSP Page</title>
    </head>
    <body>
        <div id="form_container">
	
		<h1><a>Session</a></h1>
		<form  method="post" action="">
					<div class="form_description">
			<h2>Nouvelle Session</h2>
			<p>Formulaire de création d'une nouvelle session</p>
		</div>						
		<ul >
			
		<li id="li_1" >
		<label  for="startDate">Date de départ : </label>
                <input/>
		<div>
			<input id="startDate" name="startDate" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label  for="endDate">Date de Fin : </label>
		<div>
			<input id="endDate" name="endDate" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label for="Max">Max : </label>
		<div>
			<input id="Max" name="Max" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label for="CourseId">Course :  </label>
		<div>
			<input id="CourseId" name="CourseId" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_5" >
		<label for="LocationId">Lieu : </label>
		<div>
			<input id="LocationId" name="LocationId" type="text" maxlength="255" value=""/> 
		</div> 
		</li>
			
					<li class="buttons">
			    
				<input id="saveForm" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
    </body>
</html>